from setuptools import setup

setup(
    name='neo4j-batch-driver',
    version='0.5',
    packages=['venv.lib.python3.6.site-packages.idna', 'venv.lib.python3.6.site-packages.pytz',
              'venv.lib.python3.6.site-packages.babel', 'venv.lib.python3.6.site-packages.babel.messages',
              'venv.lib.python3.6.site-packages.babel.localtime', 'venv.lib.python3.6.site-packages.jinja2',
              'venv.lib.python3.6.site-packages.sphinx', 'venv.lib.python3.6.site-packages.sphinx.cmd',
              'venv.lib.python3.6.site-packages.sphinx.ext', 'venv.lib.python3.6.site-packages.sphinx.ext.autodoc',
              'venv.lib.python3.6.site-packages.sphinx.ext.napoleon',
              'venv.lib.python3.6.site-packages.sphinx.ext.autosummary', 'venv.lib.python3.6.site-packages.sphinx.util',
              'venv.lib.python3.6.site-packages.sphinx.util.stemmer', 'venv.lib.python3.6.site-packages.sphinx.locale',
              'venv.lib.python3.6.site-packages.sphinx.pycode', 'venv.lib.python3.6.site-packages.sphinx.search',
              'venv.lib.python3.6.site-packages.sphinx.domains', 'venv.lib.python3.6.site-packages.sphinx.testing',
              'venv.lib.python3.6.site-packages.sphinx.writers', 'venv.lib.python3.6.site-packages.sphinx.builders',
              'venv.lib.python3.6.site-packages.sphinx.builders.latex',
              'venv.lib.python3.6.site-packages.sphinx.directives',
              'venv.lib.python3.6.site-packages.sphinx.transforms',
              'venv.lib.python3.6.site-packages.sphinx.transforms.post_transforms',
              'venv.lib.python3.6.site-packages.sphinx.websupport',
              'venv.lib.python3.6.site-packages.sphinx.websupport.search',
              'venv.lib.python3.6.site-packages.sphinx.websupport.storage',
              'venv.lib.python3.6.site-packages.sphinx.environment',
              'venv.lib.python3.6.site-packages.sphinx.environment.adapters',
              'venv.lib.python3.6.site-packages.sphinx.environment.collectors',
              'venv.lib.python3.6.site-packages.certifi', 'venv.lib.python3.6.site-packages.chardet',
              'venv.lib.python3.6.site-packages.chardet.cli', 'venv.lib.python3.6.site-packages.urllib3',
              'venv.lib.python3.6.site-packages.urllib3.util', 'venv.lib.python3.6.site-packages.urllib3.contrib',
              'venv.lib.python3.6.site-packages.urllib3.contrib._securetransport',
              'venv.lib.python3.6.site-packages.urllib3.packages',
              'venv.lib.python3.6.site-packages.urllib3.packages.backports',
              'venv.lib.python3.6.site-packages.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.6.site-packages.docutils', 'venv.lib.python3.6.site-packages.docutils.utils',
              'venv.lib.python3.6.site-packages.docutils.utils.math',
              'venv.lib.python3.6.site-packages.docutils.parsers',
              'venv.lib.python3.6.site-packages.docutils.parsers.rst',
              'venv.lib.python3.6.site-packages.docutils.parsers.rst.languages',
              'venv.lib.python3.6.site-packages.docutils.parsers.rst.directives',
              'venv.lib.python3.6.site-packages.docutils.readers', 'venv.lib.python3.6.site-packages.docutils.writers',
              'venv.lib.python3.6.site-packages.docutils.writers.xetex',
              'venv.lib.python3.6.site-packages.docutils.writers.latex2e',
              'venv.lib.python3.6.site-packages.docutils.writers.odf_odt',
              'venv.lib.python3.6.site-packages.docutils.writers.s5_html',
              'venv.lib.python3.6.site-packages.docutils.writers.pep_html',
              'venv.lib.python3.6.site-packages.docutils.writers.html4css1',
              'venv.lib.python3.6.site-packages.docutils.writers.html5_polyglot',
              'venv.lib.python3.6.site-packages.docutils.languages',
              'venv.lib.python3.6.site-packages.docutils.transforms', 'venv.lib.python3.6.site-packages.pygments',
              'venv.lib.python3.6.site-packages.pygments.lexers', 'venv.lib.python3.6.site-packages.pygments.styles',
              'venv.lib.python3.6.site-packages.pygments.filters',
              'venv.lib.python3.6.site-packages.pygments.formatters', 'venv.lib.python3.6.site-packages.requests',
              'venv.lib.python3.6.site-packages.alabaster', 'venv.lib.python3.6.site-packages.packaging',
              'venv.lib.python3.6.site-packages.markupsafe',
              'venv.lib.python3.6.site-packages.sphinxcontrib.websupport',
              'venv.lib.python3.6.site-packages.sphinxcontrib.websupport.search',
              'venv.lib.python3.6.site-packages.sphinxcontrib.websupport.storage',
              'venv.lib.python3.6.site-packages.snowballstemmer',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip.req',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip.vcs',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip.utils',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip.compat',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip.models',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.distlib',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.distlib._backport',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.colorama',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib._trie',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib.filters',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib.treewalkers',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib.treeadapters',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib.treebuilders',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.lockfile',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.progress',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.chardet',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.urllib3',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.urllib3.util',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.urllib3.contrib',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.urllib3.packages',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.packaging',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.cachecontrol',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.cachecontrol.caches',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.webencodings',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.pkg_resources',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip.commands',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip.operations',
              'venv.lib64.python3.6.site-packages.idna', 'venv.lib64.python3.6.site-packages.pytz',
              'venv.lib64.python3.6.site-packages.babel', 'venv.lib64.python3.6.site-packages.babel.messages',
              'venv.lib64.python3.6.site-packages.babel.localtime', 'venv.lib64.python3.6.site-packages.jinja2',
              'venv.lib64.python3.6.site-packages.sphinx', 'venv.lib64.python3.6.site-packages.sphinx.cmd',
              'venv.lib64.python3.6.site-packages.sphinx.ext', 'venv.lib64.python3.6.site-packages.sphinx.ext.autodoc',
              'venv.lib64.python3.6.site-packages.sphinx.ext.napoleon',
              'venv.lib64.python3.6.site-packages.sphinx.ext.autosummary',
              'venv.lib64.python3.6.site-packages.sphinx.util',
              'venv.lib64.python3.6.site-packages.sphinx.util.stemmer',
              'venv.lib64.python3.6.site-packages.sphinx.locale', 'venv.lib64.python3.6.site-packages.sphinx.pycode',
              'venv.lib64.python3.6.site-packages.sphinx.search', 'venv.lib64.python3.6.site-packages.sphinx.domains',
              'venv.lib64.python3.6.site-packages.sphinx.testing', 'venv.lib64.python3.6.site-packages.sphinx.writers',
              'venv.lib64.python3.6.site-packages.sphinx.builders',
              'venv.lib64.python3.6.site-packages.sphinx.builders.latex',
              'venv.lib64.python3.6.site-packages.sphinx.directives',
              'venv.lib64.python3.6.site-packages.sphinx.transforms',
              'venv.lib64.python3.6.site-packages.sphinx.transforms.post_transforms',
              'venv.lib64.python3.6.site-packages.sphinx.websupport',
              'venv.lib64.python3.6.site-packages.sphinx.websupport.search',
              'venv.lib64.python3.6.site-packages.sphinx.websupport.storage',
              'venv.lib64.python3.6.site-packages.sphinx.environment',
              'venv.lib64.python3.6.site-packages.sphinx.environment.adapters',
              'venv.lib64.python3.6.site-packages.sphinx.environment.collectors',
              'venv.lib64.python3.6.site-packages.certifi', 'venv.lib64.python3.6.site-packages.chardet',
              'venv.lib64.python3.6.site-packages.chardet.cli', 'venv.lib64.python3.6.site-packages.urllib3',
              'venv.lib64.python3.6.site-packages.urllib3.util', 'venv.lib64.python3.6.site-packages.urllib3.contrib',
              'venv.lib64.python3.6.site-packages.urllib3.contrib._securetransport',
              'venv.lib64.python3.6.site-packages.urllib3.packages',
              'venv.lib64.python3.6.site-packages.urllib3.packages.backports',
              'venv.lib64.python3.6.site-packages.urllib3.packages.ssl_match_hostname',
              'venv.lib64.python3.6.site-packages.docutils', 'venv.lib64.python3.6.site-packages.docutils.utils',
              'venv.lib64.python3.6.site-packages.docutils.utils.math',
              'venv.lib64.python3.6.site-packages.docutils.parsers',
              'venv.lib64.python3.6.site-packages.docutils.parsers.rst',
              'venv.lib64.python3.6.site-packages.docutils.parsers.rst.languages',
              'venv.lib64.python3.6.site-packages.docutils.parsers.rst.directives',
              'venv.lib64.python3.6.site-packages.docutils.readers',
              'venv.lib64.python3.6.site-packages.docutils.writers',
              'venv.lib64.python3.6.site-packages.docutils.writers.xetex',
              'venv.lib64.python3.6.site-packages.docutils.writers.latex2e',
              'venv.lib64.python3.6.site-packages.docutils.writers.odf_odt',
              'venv.lib64.python3.6.site-packages.docutils.writers.s5_html',
              'venv.lib64.python3.6.site-packages.docutils.writers.pep_html',
              'venv.lib64.python3.6.site-packages.docutils.writers.html4css1',
              'venv.lib64.python3.6.site-packages.docutils.writers.html5_polyglot',
              'venv.lib64.python3.6.site-packages.docutils.languages',
              'venv.lib64.python3.6.site-packages.docutils.transforms', 'venv.lib64.python3.6.site-packages.pygments',
              'venv.lib64.python3.6.site-packages.pygments.lexers',
              'venv.lib64.python3.6.site-packages.pygments.styles',
              'venv.lib64.python3.6.site-packages.pygments.filters',
              'venv.lib64.python3.6.site-packages.pygments.formatters', 'venv.lib64.python3.6.site-packages.requests',
              'venv.lib64.python3.6.site-packages.alabaster', 'venv.lib64.python3.6.site-packages.packaging',
              'venv.lib64.python3.6.site-packages.markupsafe',
              'venv.lib64.python3.6.site-packages.sphinxcontrib.websupport',
              'venv.lib64.python3.6.site-packages.sphinxcontrib.websupport.search',
              'venv.lib64.python3.6.site-packages.sphinxcontrib.websupport.storage',
              'venv.lib64.python3.6.site-packages.snowballstemmer',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip.req',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip.vcs',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip.utils',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip.compat',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip.models',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.distlib',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.distlib._backport',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.colorama',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib._trie',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib.filters',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib.treewalkers',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib.treeadapters',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib.treebuilders',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.lockfile',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.progress',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.chardet',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.urllib3',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.urllib3.util',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.urllib3.contrib',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.urllib3.packages',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.packaging',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.cachecontrol',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.cachecontrol.caches',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.webencodings',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.pkg_resources',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip.commands',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip.operations'],
    url='textkernel.com',
    license='LGPL v3',
    author='JJ Bankert, Textkernel',
    author_email='',
    description='Neo4j single-transaction HTTP API driver for Python'
)
